/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.OdabraniTrening;

import domen.Korisnik;
import domen.OdabraniTrening;
import domen.OpstiDomenskiObjekat;
import domen.Trening;
import forma.Korisnik.IzmenaKorisnika;
import forma.Korisnik.PretragaKorisnika;
import forma.Korisnik.PrikazKorisnika;
import forma.Korisnik.UnosKorisnika;
import forma.OdabraniTrening.model.TableModelOdabraniTreninzi;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Roki
 */
public class PretragaOdabranogTreninga extends javax.swing.JFrame {

    TableModelOdabraniTreninzi tmot;

    /**
     * Creates new form PretragaOdabranogTreninga
     */
    public PretragaOdabranogTreninga() {

        initComponents();
        setLocationRelativeTo(null);
        inicijalizujKorisnike();
        inizijalizujTreninge();
        inizijalizujStatus();
        tmot = new TableModelOdabraniTreninzi();
        tblOdabraniTr.setModel(tmot);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbxKorisnik = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbxTreninzi = new javax.swing.JComboBox();
        btnPretraga = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbxStatus = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOdabraniTr = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        btnUnesiNovi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[TERETANA] Pretraga odabranih treninga");

        jLabel1.setText("Korisnik:");

        jLabel2.setText("Trening:");

        btnPretraga.setText("Pretraži");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        jLabel3.setText("Status:");

        cmbxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxStatusActionPerformed(evt);
            }
        });

        tblOdabraniTr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOdabraniTr);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setText("Prikaži");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnUnesiNovi.setText("Unesi novi");
        btnUnesiNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNoviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbxKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbxTreninzi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnesiNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbxKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbxTreninzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPretraga)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesiNovi)
                    .addComponent(btnPrikazi)
                    .addComponent(btnIzmeni))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNoviActionPerformed
        JDialog dijalog = new JDialog(PretragaOdabranogTreninga.this, "[TERETANA] Unos novog odabranog treninga", false);
        UnosOdabranogTreninga un = new UnosOdabranogTreninga();
        dijalog.add(un);
        dijalog.setSize(555, 555);
        dijalog.setLocationRelativeTo(this);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_btnUnesiNoviActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int selektovanRed = tblOdabraniTr.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red.");
            return;
        }
        popuniSesiju(selektovanRed);
        JDialog dijalog = new JDialog(PretragaOdabranogTreninga.this, "[TERETANA] Prikaz odabranog treninga", true);
        PrikazOdabranogTreninga pk = new PrikazOdabranogTreninga();
        dijalog.add(pk);
        dijalog.setSize(555, 555);
        dijalog.setLocationRelativeTo(this);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int selektovanRed = tblOdabraniTr.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red.");
            return;
        }
        popuniSesiju(selektovanRed);
        JDialog dijalog = new JDialog(PretragaOdabranogTreninga.this, "[TERETANA] Izmena odabranog treninga", true);
        IzmenaOdabranogTreninga ik = new IzmenaOdabranogTreninga();
        dijalog.add(ik);
        dijalog.setSize(555, 555);
        dijalog.setLocationRelativeTo(this);
        dijalog.pack();
        dijalog.setVisible(true);

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        //String jed = (String) cmbxKorisnik.getSelectedItem();
        //String jed2 = (String) cmbxStatus.getSelectedItem();
        //String jed3 = (String) cmbxTreninzi.getSelectedItem();

        Korisnik kor = null;
        Trening tr = null;
        String status = "";

        if (cmbxKorisnik.getSelectedItem().equals("")) {
            if (cmbxStatus.getSelectedItem().equals("")) {
                if (cmbxTreninzi.getSelectedItem().equals("")) {
                    JOptionPane.showMessageDialog(this, "Morate odabrati barem jedan kriterijum.");
                    return;
                }
            }
        }

        if (!cmbxKorisnik.getSelectedItem().equals("")) {
            kor = (Korisnik) cmbxKorisnik.getSelectedItem();
        }
        if (!cmbxStatus.getSelectedItem().equals("")) {
            status = (String) cmbxStatus.getSelectedItem();
        }
        if (!cmbxTreninzi.getSelectedItem().equals("")) {
            tr = (Trening) cmbxTreninzi.getSelectedItem();
        }

        try {
            tmot.setOdTreninzi(kontroler.Kontroler.getInstance().pretraziOdabraneTreninge(kor, tr, status));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void cmbxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaOdabranogTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaOdabranogTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaOdabranogTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaOdabranogTreninga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaOdabranogTreninga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnUnesiNovi;
    private javax.swing.JComboBox cmbxKorisnik;
    private javax.swing.JComboBox cmbxStatus;
    private javax.swing.JComboBox cmbxTreninzi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOdabraniTr;
    // End of variables declaration//GEN-END:variables

    private void popuniSesiju(int selektovanRed) {
        OdabraniTrening ot = tmot.getOdTreninzi().get(selektovanRed);
        sesija.Sesija.getInstance().setObjekat(null);
        sesija.Sesija.getInstance().setObjekat(ot);
    }

    private void inicijalizujKorisnike() {
        try {
            ArrayList<Korisnik> listaKorisnika = kontroler.Kontroler.getInstance().vratiSveKorisnike();
            cmbxKorisnik.addItem("");

            for (Korisnik korisnik : listaKorisnika) {
                cmbxKorisnik.addItem(korisnik);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "GRESKA - korisnici");
            return;
        }
    }

    private void inizijalizujTreninge() {
        try {
            ArrayList<Trening> listaTreninga = kontroler.Kontroler.getInstance().vratiSveTreninge();
            cmbxTreninzi.addItem("");
            for (Trening trening : listaTreninga) {
                cmbxTreninzi.addItem(trening);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "GRESKA - treninzi");
            return;
        }
    }

    private void inizijalizujStatus() {
        cmbxStatus.addItem("");
        cmbxStatus.addItem("Važeći");
        cmbxStatus.addItem("Nevažeći");
    }

}
