/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.Korisnik;

import domen.Korisnik;
import domen.Radnik;
import forma.Korisnik.model.TableModelKorisnik;
import forma.OdabraniTrening.UnosOdabranogTreninga;
import java.awt.Dialog;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author Roki
 */
public class PretragaKorisnika extends javax.swing.JFrame {

    TableModelKorisnik tmk;

    /**
     * Creates new form FormaPrikazKorisnika
     */
    public PretragaKorisnika() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        tmk = new TableModelKorisnik();
        tabelaKorisnici.setModel(tmk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRadnikKojiJeUneo = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaKorisnici = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        btnUnos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[TERETANA] Korisnici");

        jLabel1.setText("ID:");

        jLabel2.setText("Ime i prezime:");

        jLabel4.setText("Radnik:");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tabelaKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaKorisnici);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setText("Prikaži");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnUnos.setText("Unesi novi");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtRadnikKojiJeUneo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtRadnikKojiJeUneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnPretrazi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPrikazi)
                    .addComponent(btnUnos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String id = txtID.getText();
        String imePrezime = txtImePrezime.getText();
        String radnikUneo = txtRadnikKojiJeUneo.getText();
        if (id.isEmpty() && imePrezime.isEmpty() && radnikUneo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Niste uneli ni jedan parametar pretrage.");
            return;
        }
        try {
            tmk.setKorisnici(kontroler.Kontroler.getInstance().pretraziKorisnike(id, imePrezime, radnikUneo));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
            return;
        }

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        JDialog dijalog = new JDialog(PretragaKorisnika.this, "[TERETANA] Unos novog korisnika", true);
        UnosKorisnika un = new UnosKorisnika();
        dijalog.add(un);
        dijalog.setSize(420, 200);
        dijalog.setLocationRelativeTo(this);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int selektovanRed = tabelaKorisnici.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red.");
            return;
        }
        popuniSesiju(selektovanRed);
        JDialog dijalog = new JDialog(PretragaKorisnika.this, "[TERETANA] Prikaz korisnika", true);
        PrikazKorisnika pk = new PrikazKorisnika();
        dijalog.add(pk);
        dijalog.setSize(420, 200);
        dijalog.setLocationRelativeTo(this);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int selektovanRed = tabelaKorisnici.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red.");
            return;
        }
        popuniSesiju(selektovanRed);
        JDialog dijalog = new JDialog(PretragaKorisnika.this, "[TERETANA] Izmena korisnika", true);
        IzmenaKorisnika ik = new IzmenaKorisnika();
        dijalog.add(ik);
        dijalog.setSize(420, 200);
        dijalog.setLocationRelativeTo(this);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaKorisnika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaKorisnika().setVisible(true);
            }
        });
    }

    public TableModelKorisnik getTmk() {
        return tmk;
    }

    public void setTmk(TableModelKorisnik tmk) {
        this.tmk = tmk;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public void setTxtID(JTextField txtID) {
        this.txtID = txtID;
    }

    public JTextField getTxtImePrezime() {
        return txtImePrezime;
    }

    public void setTxtImePrezime(JTextField txtImePrezime) {
        this.txtImePrezime = txtImePrezime;
    }

    public JTextField getTxtRadnikKojiJeUneo() {
        return txtRadnikKojiJeUneo;
    }

    public void setTxtRadnikKojiJeUneo(JTextField txtRadnikKojiJeUneo) {
        this.txtRadnikKojiJeUneo = txtRadnikKojiJeUneo;
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public void setBtnIzmeni(JButton btnIzmeni) {
        this.btnIzmeni = btnIzmeni;
    }

    public JButton getBtnPretrazi() {
        return btnPretrazi;
    }

    public void setBtnPretrazi(JButton btnPretrazi) {
        this.btnPretrazi = btnPretrazi;
    }

    public JButton getBtnPrikazi() {
        return btnPrikazi;
    }

    public void setBtnPrikazi(JButton btnPrikazi) {
        this.btnPrikazi = btnPrikazi;
    }

    public JToggleButton getBtnUnos() {
        return btnUnos;
    }

    public void setBtnUnos(JToggleButton btnUnos) {
        this.btnUnos = btnUnos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JToggleButton btnUnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaKorisnici;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtRadnikKojiJeUneo;
    // End of variables declaration//GEN-END:variables

    public void popuniSesiju(int selektovanRed) {
        int id = (int) tabelaKorisnici.getValueAt(selektovanRed, 0);
        String ime = (String) tabelaKorisnici.getValueAt(selektovanRed, 1);
        String email = (String) tabelaKorisnici.getValueAt(selektovanRed, 2);
        String telefon = (String) tabelaKorisnici.getValueAt(selektovanRed, 3);
        Radnik r = (Radnik) tabelaKorisnici.getValueAt(selektovanRed, 4);
        Korisnik k = new Korisnik(id, ime, email, telefon, r);
        sesija.Sesija.getInstance().setObjekat(null);
        sesija.Sesija.getInstance().setObjekat(k);
    }

}
